### ISSUE TITLE
Invalid email address passes basic validation

### ISSUE THREAD

**Issue by alinlacea** [zulumarketing/validate-email-address#1]
Hello,

It seems that the following lines of code return True, even though they shouldn't:
```python
>>> from validate_email_address import validate_email
>>> validate_email("sdfas@dd")
True

```

I'm not sure why this happens.
Thanks

**Comment by xj9** [comment]
That is a valid email address according to RFC 2822, however if you need know that the email address actually exists you should do:

```python
>>> from validate_email_address import validate_email
>>> validate_email('sdfas@dd', verify=True)
```
