### ISSUE TITLE
does not check for domain extension.

### ISSUE THREAD

**Issue by sbhushan** [zulumarketing/validate-email-address#3]
<code>
In [1]: from validate_email_address import validate_email

In [2]: validate_email("admin@domain.")
Out[2]: False

In [3]: validate_email("admin@domain")
Out[3]: True
</code>

**Comment by xj9** [comment]
`admin@domain` *is* a valid email address. It may not always be routable, but it is still valid. You can check if the address is reachable by passing `verify=True` or `check_mx=True`. These do not run by default because they talk to the network, which can be slow.
